// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTTaskType = "t_task_type"

// TTaskType 任务类型策略配置表
type TTaskType struct {
	TypeID              string    `gorm:"column:type_id;primaryKey;comment:任务类型ID(如email/sms)" json:"type_id"`                          // 任务类型ID(如email/sms)
	SchedulePolicy      string    `gorm:"column:schedule_policy;not null;comment:调度策略(JSON格式, 含CRON/FIX_RATE等)" json:"schedule_policy"` // 调度策略(JSON格式, 含CRON/FIX_RATE等)
	RetryPolicy         string    `gorm:"column:retry_policy;not null;comment:重试策略(JSON格式,含max_retries/backoff等)" json:"retry_policy"`  // 重试策略(JSON格式,含max_retries/backoff等)
	Priority            int32     `gorm:"column:priority;not null;default:5;comment:默认优先级(1-10)" json:"priority"`                       // 默认优先级(1-10)
	ShardCount          int32     `gorm:"column:shard_count;not null;default:4;comment:该类型默认分片数" json:"shard_count"`                    // 该类型默认分片数
	EnableDynamicConfig bool      `gorm:"column:enable_dynamic_config;comment:是否允许任务覆盖配置" json:"enable_dynamic_config"`                 // 是否允许任务覆盖配置
	CreateTime          time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime          time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName TTaskType's table name
func (*TTaskType) TableName() string {
	return TableNameTTaskType
}
