services:
  mysql:
    image: mysql:8.0
    container_name: go-job-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_job
      - TZ=Asia/Shanghai
    # volumes:
      # - ./data/db/sql/ini:/docker-entrypoint-initdb.d

  redis:
    image: "redis:7.0-alpine"
    container_name: go-job-redis
    ports:
      - "6379:6379"